trigger:
  branches:
    include:
      - main
      - feature/*

stages:

# ✅ Stage 1: Terraform Init
- stage: TerraformInit
  displayName: "Terraform Init"
  jobs:
    - job: InitJob
      displayName: "Initialize Terraform"
      pool:
        name: agent-ka-pool
      steps:
        - task: TerraformInstaller@1
          displayName: 'Install Terraform'
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          displayName: 'Terraform Init'
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/module'
            backendServiceArm: 'servocon'
            backendAzureRmStorageAccountName: 'stgstage'
            backendAzureRmContainerName: 'cntstage'
            backendAzureRmKey: 'stage.tfstate'

# ✅ Stage 2: Terraform Plan
- stage: TerraformPlan
  displayName: "Terraform Plan"
  dependsOn: TerraformInit
  jobs:
    - job: PlanJob
      displayName: "Terraform Plan"
      pool:
        name: agent-ka-pool
      steps:
        - task: TerraformInstaller@1
          displayName: 'Install Terraform'
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          displayName: 'Terraform Init (before Plan)'
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/module'
            backendServiceArm: 'servocon'
            backendAzureRmStorageAccountName: 'stgstage'
            backendAzureRmContainerName: 'cntstage'
            backendAzureRmKey: 'stage.tfstate'

        - task: TerraformTask@5
          displayName: 'Terraform Plan'
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/module'
            environmentServiceNameAzureRM: 'servocon'

# ✅ Stage 3: Manual Approval
- stage: ManualApproval
  displayName: "Manual Validation"
  dependsOn: TerraformPlan
  jobs:
    - job: ApprovalJob
      displayName: "Manual Approval"
      pool:
        name: server
      steps:
        - task: ManualValidation@0
          inputs:
            instructions: 'Please review Terraform Plan. Approve to proceed with Apply.'
            onTimeout: 'reject'
            timeout: '1h'

# ✅ Stage 4: Terraform Apply
- stage: TerraformApply
  displayName: "Terraform Apply"
  dependsOn: ManualApproval
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
    - job: ApplyJob
      displayName: "Terraform Apply"
      pool:
        name: agent-ka-pool
      steps:
        - task: TerraformInstaller@1
          displayName: 'Install Terraform'
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          displayName: 'Terraform Init (Again in Apply)'
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/module'
            backendServiceArm: 'servocon'
            backendAzureRmStorageAccountName: 'stgstage'
            backendAzureRmContainerName: 'cntstage'
            backendAzureRmKey: 'stage.tfstate'

        - task: TerraformTask@5
          displayName: 'Terraform Apply'
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/module'
            environmentServiceNameAzureRM: 'servocon'
